# Generated by Django 5.0.4 on 2024-05-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelecomBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('date', models.DateField()),
                ('phone_number_email', models.CharField(max_length=100)),
                ('operation_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('subscription_number', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('date', models.DateField()),
                ('gov', models.CharField(max_length=100)),
                ('operation_number', models.CharField(max_length=100)),
                ('billing_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('subscription_number', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('date', models.DateField()),
                ('gov', models.CharField(max_length=100)),
                ('operation_number', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(max_length=100)),
                ('barcode_number', models.CharField(max_length=100)),
                ('counter_number', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
