# Generated by Django 5.0.4 on 2024-05-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelecomBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default='11:11')),
                ('provider', models.CharField(default='SyriatelSEP', max_length=100)),
                ('operation_number', models.CharField(max_length=100)),
                ('phone_number_email', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('subscription_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default='11:11')),
                ('provider', models.CharField(default='SyriatelSEP', max_length=100)),
                ('operation_number', models.CharField(max_length=100)),
                ('gov', models.CharField(max_length=100)),
                ('billing_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('subscription_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default='11:11')),
                ('provider', models.CharField(default='SyriatelSEP', max_length=100)),
                ('operation_number', models.CharField(max_length=100)),
                ('gov', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(max_length=100)),
                ('barcode_number', models.CharField(max_length=100)),
                ('counter_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
