# Generated by Django 5.0.4 on 2024-05-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricbill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='telecombill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='waterbill',
            old_name='user_id',
            new_name='user',
        ),
    ]
