# Generated by Django 5.0.4 on 2024-05-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_telecombill_subscription_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telecombill',
            name='user',
        ),
    ]
