# Generated by Django 5.0.4 on 2024-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_id_electricbill_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='electricbill',
            name='provider',
            field=models.CharField(default='SyriatelSEP', max_length=100),
        ),
        migrations.AddField(
            model_name='telecombill',
            name='provider',
            field=models.CharField(default='SyriatelSEP', max_length=100),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='provider',
            field=models.CharField(default='SyriatelSEP', max_length=100),
        ),
    ]
