# Generated by Django 5.0.4 on 2024-05-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_telecombill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecombill',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
