# Generated by Django 5.0.4 on 2024-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_item_electricbill_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbill',
            name='time',
            field=models.TimeField(default='11:11'),
        ),
        migrations.AddField(
            model_name='telecombill',
            name='time',
            field=models.TimeField(default='11:11'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='time',
            field=models.TimeField(default='11:11'),
        ),
    ]
