# Generated by Django 5.0.4 on 2024-05-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_last_el_bill_user_last_tel_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_el_bill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_tel_bill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_wa_bill',
        ),
    ]
