# Generated by Django 5.0.4 on 2024-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_last_el_bill_remove_user_last_tel_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbill',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telecombill',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
