# Generated by Django 5.0.4 on 2024-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_electricbill_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbill',
            name='operation_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='telecombill',
            name='operation_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='operation_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
